steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/the-gram-feed:$SHORT_SHA", "."]
  - name: gcr.io/$PROJECT_ID/sonar-scanner:latest
    args:
      - "-Dsonar.host.url=https://sonarcloud.io"
      - "-Dsonar.login=${_SONAR_KEY_TOMMY}"
      - "-Dsonar.organization=tommygoossens"
      - "-Dsonar.projectKey=TommyGoossens_the-gram-feed"
      - "-Dsonar.sources=."
      - "-Dsonar.branch.name=master"

  # - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  #   args:
  #   - '-Dsonar.host.url=https://sonarcloud.io'
  #   - '-Dsonar.login=${_SONAR_KEY_TOMMY}'
  #   - '-Dsonar.projectKey=TommyGoossens_the-gram-feed'
  #   - '-Dsonar.organization=tommygoossens'
  #   - '-Dsonar.sources=.'
  # tags: ['cloud-builders-community']

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/the-gram-feed:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=k8s-feed-config.yaml
      - --image=gcr.io/$PROJECT_ID/the-gram-feed:$SHORT_SHA
      - --location=europe-west1-b
      - --cluster=the-gram-k8s
