apiVersion: v1
kind: ServiceAccount
metadata:
  name: the-gram
---
apiVersion: v1
kind: Service
metadata:
  name: the-gram-feed-service
spec:
  type: NodePort
  selector:
    app: the-gram-feed
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-gram-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-gram-feed
  template:
    metadata:
      labels:
        app: the-gram-feed
    spec:
      containers:
        - name: the-gram-feed
          image: tommygoossens/the-gram-feed:latest
          ports:
            - containerPort: 80
              name: http
      serviceAccountName: the-gram
